### ISSUE TITLE
Elements in arrays should have a "key" prop.

### ISSUE THREAD

**Issue by fiatjaf** [constantoduol/JSONEditor#2]
I'm getting the classic React error for when elements of an array of children don't have a "key" element. I suspect it is the `elems` array that is build for each JSON document with many `elems.push()` calls.

**Comment by constantoduol** [comment]
Will take a look at this, thanks for reporting @fiatjaf

**Comment by alvesl** [comment]
+1

**Comment by constantoduol** [comment]
Resolved by https://github.com/constantoduol/JSONEditor/commit/26d0e14c5078107a681356704bfa16e926548502
