### ISSUE TITLE
how can i edit json?

### ISSUE THREAD

**Issue by Master-H** [constantoduol/JSONEditor#4]
there is not a document to show how can eidt json, it just only show json data ?

**Comment by constantoduol** [comment]
The information on how to edit json is in the README.md on the home page of this repository. To edit a json object you pass it in to the `JSONEditor` component which will render an editable view that you can edit existing elements or add new ones .

```javascript

function onJsonChange(key, value, parent, data){
   console.log(key, value, parent, data);
}

<JSONEditor 
     data={{name: "sam", age: 20}}
     onChange={onJsonChange}
/>

**Comment by constantoduol** [comment]
Closing as resolved
