### ISSUE TITLE
feature request - make styles configurable

### ISSUE THREAD

**Issue by demorphica** [constantoduol/JSONEditor#6]
hi @constantoduol ```styles``` defined here - https://github.com/constantoduol/JSONEditor/blob/58acc92d3a3f5cb6d3e9accf3dd3cac93e9c403b/src/lib/JSONEditor.js#L468 is currently not configurable so afaik styling is impossible without using something like :global using some library such as this - https://github.com/zeit/styled-jsx#styling-third-parties--child-components-from-the-parent. 
That also does not solve the problem since all elements are ```div``` & so for eg. i can't figure out a way to style font for different elements.

I raised the issue since i'm working with a dark theme, & readability is becoming a problem

![image](https://user-images.githubusercontent.com/3260659/61164524-a748ec00-a533-11e9-8214-81c0ae47645f.png)

Is there any other way this can be solved without you having to make changes to the library?

If not, from what i understand, there could be more that one way to implement this, eg. (listing from my own understanding of how much time it would take to implement)
1. remove ```styles``` from the code, add it a new object prop for styles, & update the README with an example of how to set a style variable from the user's JS using the current ```styles``` variable as an example
2. make styles an optional object prop with a default value equal to the current styles variable, so user can override style from their own JS if they want to, update README with example of how to send the styles as an object prop
3. add className to all elements, let user handle styling using their own CSS/LESS, but since eg. ```label``` ```value``` ```row``` & ```root``` are very generic names these probably need to be renamed to be more unique to JSONEditor. Update README with how to create an example .css file to set the styles

Of course, there would also be other ways, also based on what you may have already thought of or prefer etc.

it would be really awesome if this feature could be added to the library

**Comment by demorphica** [comment]
1 more scrshot, the blue font is the most difficult to read

![image](https://user-images.githubusercontent.com/3260659/61164855-e2005380-a536-11e9-9314-4f317b6c591f.png)

**Comment by constantoduol** [comment]
Thanks for this. Will assess the amount of work required and update this issue.

**Comment by constantoduol** [comment]
Fixe
